apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-in-app
  namespace: argocd
spec:
  project: my-local-project

  source:
    repoURL: https://github.com/ronakforgit/argo-manifest.git
    targetRevision: HEAD
    path: argocd-apps
  destination: 
    server: https://kubernetes.default.svc
    namespace: demoenv

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true