apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pythonapp
  labels:
    app: python
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: python
        octopusexport: OctopusExport
    spec:
      containers:
        - name: pythonflaskapp
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
