apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application3
  namespace: my-local-project
spec:
  project: default

  source:
    repoURL: https://github.com/ronakforgit/argo-manifest.git
    targetRevision: HEAD
    path: my-apps/app-3
  destination: 
    server: https://kubernetes.default.svc
    namespace: demoenv

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true