apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-1
  labels:
    app: nginx-app-1
spec:
  selector:
    matchLabels:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-app-1
    spec:
      containers:
        - name: nginx-app-1
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
